# Generated by Django 4.1.7 on 2023-06-02 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=100, null=True)),
                ('SubjectTopics', models.CharField(max_length=100, null=True)),
                ('Material', models.FileField(blank=True, null=True, upload_to='records/material')),
            ],
            options={
                'db_table': 'StudyMaterial',
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100, null=True)),
                ('TestTopics', models.CharField(max_length=100, null=True)),
                ('Material', models.FileField(blank=True, null=True, upload_to='records/results')),
            ],
            options={
                'db_table': 'TestResults',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100, null=True)),
                ('TestTopics', models.CharField(max_length=100, null=True)),
                ('TestScore', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployeeExp1',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostGraduation', models.CharField(max_length=100, null=True)),
                ('CollegePG', models.CharField(max_length=100, null=True)),
                ('YearOfPassing1', models.CharField(max_length=100, null=True)),
                ('PGPercentage', models.CharField(max_length=100, null=True)),
                ('Graduation', models.CharField(max_length=100, null=True)),
                ('CollegeGraduation', models.CharField(max_length=100, null=True)),
                ('YearOfPassing2', models.CharField(max_length=100, null=True)),
                ('GraduationPercentage', models.CharField(max_length=100, null=True)),
                ('CourseHSC', models.CharField(max_length=100, null=True)),
                ('CollegeHSC', models.CharField(max_length=100, null=True)),
                ('YearOfPassing3', models.CharField(max_length=100, null=True)),
                ('HSCPercentage', models.CharField(max_length=100, null=True)),
                ('CourseSSC', models.CharField(max_length=100, null=True)),
                ('CollegeSSC', models.CharField(max_length=100, null=True)),
                ('YearOfPassing4', models.CharField(max_length=100, null=True)),
                ('SSCPercentage', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployeeEDU1',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('Ecode', models.IntegerField()),
                ('Edesignation', models.CharField(max_length=100)),
                ('Econtact', models.IntegerField(null=True)),
                ('BatchName', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cover', models.FileField(blank=True, null=True, upload_to='records/covers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employee_RMS1',
            },
        ),
    ]
