# Generated by Django 4.0.1 on 2022-03-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee_RMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecreate',
            name='Econtact',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='EmployeeExperienc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company1Name', models.CharField(max_length=100, null=True)),
                ('Company1Desig', models.CharField(max_length=100, null=True)),
                ('Company1Duration', models.CharField(max_length=100, null=True)),
                ('Company1salary', models.IntegerField(null=True)),
                ('Company2Name', models.CharField(max_length=100, null=True)),
                ('Company2Desig', models.CharField(max_length=100, null=True)),
                ('Company2Duration', models.CharField(max_length=100, null=True)),
                ('Company2salary', models.IntegerField(null=True)),
                ('Company3Name', models.CharField(max_length=100, null=True)),
                ('Company3Desig', models.CharField(max_length=100, null=True)),
                ('Company3Duration', models.CharField(max_length=100, null=True)),
                ('Company3salary', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployeeExp',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostGraduation', models.CharField(max_length=100, null=True)),
                ('CollegePG', models.CharField(max_length=100, null=True)),
                ('PGPercentage', models.CharField(max_length=100, null=True)),
                ('Graduation', models.CharField(max_length=100, null=True)),
                ('CollegeGraduation', models.CharField(max_length=100, null=True)),
                ('GraduationPercentage', models.CharField(max_length=100, null=True)),
                ('CourseHSC', models.CharField(max_length=100, null=True)),
                ('CollegeHSC', models.CharField(max_length=100, null=True)),
                ('HSCPercentage', models.CharField(max_length=100, null=True)),
                ('CourseSSC', models.CharField(max_length=100, null=True)),
                ('CollegeSSC', models.CharField(max_length=100, null=True)),
                ('YearOfPassing', models.CharField(max_length=100, null=True)),
                ('SSCPercentage', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployeeEDU',
            },
        ),
    ]
