# Generated by Django 4.0.1 on 2022-03-03 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee_RMS', '0002_alter_employeecreate_econtact_employeeexperienc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeExperienc',
            new_name='EmployeeExperience',
        ),
    ]
