# Generated by Django 4.0.1 on 2022-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_RMS', '0003_rename_employeeexperienc_employeeexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='Company1salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Company2salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Company3salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
