# Generated by Django 4.0.1 on 2022-03-03 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee_RMS', '0004_alter_employeeexperience_company1salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostGraduation', models.CharField(max_length=100, null=True)),
                ('CollegePG', models.CharField(max_length=100, null=True)),
                ('YearOfPassing1', models.CharField(max_length=100, null=True)),
                ('PGPercentage', models.CharField(max_length=100, null=True)),
                ('Graduation', models.CharField(max_length=100, null=True)),
                ('CollegeGraduation', models.CharField(max_length=100, null=True)),
                ('YearOfPassing2', models.CharField(max_length=100, null=True)),
                ('GraduationPercentage', models.CharField(max_length=100, null=True)),
                ('CourseHSC', models.CharField(max_length=100, null=True)),
                ('CollegeHSC', models.CharField(max_length=100, null=True)),
                ('YearOfPassing3', models.CharField(max_length=100, null=True)),
                ('HSCPercentage', models.CharField(max_length=100, null=True)),
                ('CourseSSC', models.CharField(max_length=100, null=True)),
                ('CollegeSSC', models.CharField(max_length=100, null=True)),
                ('YearOfPassing4', models.CharField(max_length=100, null=True)),
                ('SSCPercentage', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployeeEDU1',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeEducation',
        ),
    ]
