# Generated by Django 2.2.28 on 2023-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_RMS', '0009_alter_employeecreate_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=100, null=True)),
                ('SubjectTopics', models.CharField(max_length=100, null=True)),
                ('Material', models.FileField(blank=True, null=True, upload_to='records/material')),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100, null=True)),
                ('TestTopics', models.CharField(max_length=100, null=True)),
                ('Material', models.FileField(blank=True, null=True, upload_to='records/results')),
            ],
        ),
        migrations.RenameField(
            model_name='employeecreate',
            old_name='Edepartment',
            new_name='BatchName',
        ),
        migrations.AlterField(
            model_name='employeecreate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeeducation1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
