# Generated by Django 2.2.28 on 2023-03-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_RMS', '0010_auto_20230303_1919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studymaterial',
            table='StudyMaterial',
        ),
        migrations.AlterModelTable(
            name='testresults',
            table='TestResults',
        ),
    ]
